version: '2'

services:
  addok:
    image: etalab/addok
    ports:
    - "7878:7878"
    volumes:
    - ./ban_data/addok.conf:/etc/addok/addok.conf
    - ./ban_data/addok.db:/data/addok.db
    - ./logs:/logs
    links:
    - addok-redis:redis
    environment:
      WORKERS: 50
      WORKER_TIMEOUT: 20
      LOG_QUERIES: 1
      LOG_NOT_FOUND: 1
      SLOW_QUERIES: 200

  addok-redis:
    image: etalab/addok-redis
    volumes:
    - ./ban_data/dump.rdb:/data/dump.rdb
